### ISSUE TITLE
[Feature] Create an endpoint to return all poll

### ISSUE THREAD

**Issue by acmesquita** [acmesquita/make-your-survey#12]
## Motivation

To see all Polls created, we need an endpoint to list all polls and show them all there on the web page `Survey`.

## Propose

1. Create a service to list all poll
2. Create in PollController the method `index` calls a service
3. Create a router to show all the polls
4. Create a page `index` to list all poll returns to API

## Tasks

- [x] Should be completed when having created a service to list all polls
- [x] Should be completed when having implementation to `index` method in controller calls service
- [x] Should be completed when having to add a router to list all poll
- [x] Should be completed when having to add a serializer to show a poll
- [x] Should be completed when having created a List component, calls a router to list all polls and show this list.
