### ISSUE TITLE
[Feature] Create an endpoint to answer a poll

### ISSUE THREAD

**Issue by acmesquita** [acmesquita/make-your-survey#21]
## Motivation

For users who can answer a poll, we need an endpoint to receive a new answer informing poll_id and option_id.

## Propose

Create a service and controller to Answer.

## Tasks

- [x] Should be completed when having created a service that knows adding a new Answer
- [x] Should be completed when having created a controller that knows to receive a poll_id and option_id using the method POST
- [x] Should be completed when having adding information who many answer to option
