### ISSUE TITLE
[Feature] Create controller and router to create a new Poll

### ISSUE THREAD

**Issue by acmesquita** [acmesquita/make-your-survey#5]
## Motivation

For to create a new Poll, we need to create a Poll controller and router.

## Propose

Create a new controller for Poll and `create` router.

## Tasks

- [ ] Should be completed when having endpoint `api/v1/poll` using method `POST` to be created
- [ ] Should be completed when having endpoint `api/v1/poll` return 201 status code if values provider is valid
- [ ] Should be completed when having endpoint `api/v1/poll` return 400 status code if values provider is invalid
- [ ] Should be completed when having endpoint `api/v1/poll` return 500 status code if an internal error
